name: jejo_radio
description: "Je Jo Radio - La tua radio sempre con te"
publish_to: none
version: 0.2.0-beta.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  cached_network_image: ^3.3.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.12
  shared_preferences: ^2.2.2
  audio_service: ^0.18.18
  google_fonts: ^6.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/countries.json
